### PR TITLE
Refactor Term storage

### LINKED ISSUE #31: Store variable images globally
In the examples we have:
```julia
julia> x, y = Variable.([:x, :y], Ref(TypeSet(Int)));

julia> normalize(@term(diff(sin(2*$x) - log($x+$y), $x)))
@term(2 * cos(2x) - 1 / (x + y))
```
It'd be nice if one could instead just declare that `x` and `y` are integers and then not have to worry about interpolating later.

### LINKED ISSUE #36: Incorrect displaying of string constants
Any `Term` should display using `@term` syntax such that pasting the `@term` displayed representation generates the same term. However, this is broken when the entire term is a string constant.

```
julia> @term("ab" * "cd")
@term("ab" * "cd")

julia> @term("abcd")
@term(abcd)
```

### LINKED ISSUE #43: Inaccurate example in the README
In the readme, you give the examples:
```julia
julia> normalize(@term(sin(α)cos(α) - cos(α)sin(α)), :TRIGONOMETRY)
@term(sin(α - α))

julia> normalize(@term(sin(α)cos(α) - cos(α)sin(α)), :BASIC, :TRIGONOMETRY)
@term(0)
```
On the current master branch however, this is not my observed behaviour:
```julia
julia> normalize(@term(sin(α)cos(α) - cos(α)sin(α)), :TRIGONOMETRY)
@term(cos(α) * sin(α) - cos(α) * sin(α))

julia> normalize(@term(sin(α)cos(α) - cos(α)sin(α)), :BASIC, :TRIGONOMETRY)
@term(zero(cos(α) * sin(α)))
```

### LINKED ISSUE #44: Improve interface for symbolic constants
I noticed today that the following does not behave as I'd expect:
```julia
julia> Rewrite.normalize((@term 1 + x + 3), @term RULES [1 + x => y])
@term(y)
```
this should return `@term(y + 3)`. Did I do something in defining the rule?

### PR DESCRIPTION
**Pull request by HarrisonGrodin**
Replaces custom storage types with a single wrapper type for `Base` AST expressions. API for generating `@term`s is much more integrated with the Julia environment used.

Closes #31, closes #44, closes #36, closes #43.

# TODO
- [x] Replace storage type
- [x] Fix matching
  - [x] Flat
  - [x] Orderless
- [x] Remove `Fn` and `Variable` aliases
- [x] Fix `CALCULUS` rules
- [x] Fix tests
- [x] Add new tests for matching with misc. `Expr` heads
- [X] Update README
- [X] Update docstrings

### CODE REVIEW

**Comment by MasonProtter** [comment]
Attaching a context to a `@term` object is possibly a very unweildly thing to do performance wise. Here's what happened with Modelling Toolkit: https://github.com/JuliaDiffEq/ModelingToolkit.jl/issues/62

Perhaps not quite analogous though

**Comment by HarrisonGrodin** [comment]
@MasonProtter Hmm. Do you have an idea for an alternative solution? So far, that's the only solution I've been able to come up with, which would unfortunately mean that (to retain the feature itself) we'd just have to accept the potential speed penalty and try to make things faster where possible.

**Comment by MasonProtter** [comment]
Yeah, that's probably reasonable. Come to think of it, Modelling Toolkit actually kept the information in the `Variable`s, ie.
```
mutable struct Variable <: Expression
    name::Symbol
    value
    value_type::DataType
    subtype::Symbol
    diff::Union{AbstractOperator,Nothing}
    dependents::Vector{Variable}
    description::String
    flow::Bool
    domain::AbstractDomain
    size
    context
end```

so maybe if a `Dict` was kept on the outermost level of a `term` object with function information then it could potentially avoid the poor scaling  `ModellingToolkit` encountered.

**Comment by HarrisonGrodin** [comment]
I've been thinking about this some more, and I realized that *most* terms shouldn't ever need to store the context on themselves. Within a given context, every [ground term](https://en.wikipedia.org/wiki/Ground_expression) should have an image which is possible to generate using only the context. Naturally, the exception is variables, which need to store the image information locally since a variable is simply a name attached to a local meaning (e.g. if a variable must be the same in 2 places, `f(x, x)`, or if the matched value is useful later, `f(x) => g(x)`).

Thus, I'm considering bringing back the `Variable` type, using the following structure (similar to previous types, but with `Fn` and `Constant` generalized into `Term`):
```julia
abstract type AbstractTerm end

struct Term{T} <: AbstractTerm
    ex::T
end

struct Variable <: AbstractTerm
    name::Symbol
    index::Integer  # variable subscript, e.g. x₁
    image::AbstractSet
end
```
It's possible that cleverly using mutation could be helpful here; in order to "synchronize" information about image set between multiple instances of a variable, the `image` set could be modified (or replaced if `Variable` is made `mutable`).

**Comment by HarrisonGrodin** [comment]
This PR now closes #36.

**Comment by HarrisonGrodin** [comment]
I've been updating `Completion`, but the more I work with it, the more I'm reminded of how separated the completion functionalities are from the rest of `Rewrite`. I've opened #47 for discussion about this.

**Pull request merged**
